% makefile

# Makefile boilerplate
default: help

PROJECT_NAME=$(shell basename "$(PWD)")
OUTPUT_FOLDER=out

.PHONY: help test
all: help
help: Makefile
	@echo
	@echo " Choose a command run in "${PROJECT_NAME}":"
	@echo
	@sed -n 's/^##//p' $< | column -t -s ':' |  sed -e 's/^/ /'
	@echo

